appConfig:
  title: Startpage
  description: Starter Dash - Lobotomized from Glance Dash
  theme: default
  icon: fas fa-home
sections:
  - name: Weatherboy Forecast
    icon: fas fa-cloud-sun
    widgets:
      - type: iframe
        options:
          url: http://192.168.1.238:5170/
          height: 300
          showTitle: true
  - name: Service Status
    icon: fas fa-server
    items:
      - title: Jellyfin
        url: http://192.168.1.238:8096
        statusCheck: true
        icon: si-jellyfin
      - title: Threadfin
        url: http://192.168.1.238:34400/web
        icon: fa-stream
        statusCheck: true
      - title: JellyFindarr
        url: http://192.168.1.78:5505
        statusCheck: true
        icon: mdi-antenna
      - title: qBittorrent
        url: http://192.168.1.85:8050
        statusCheck: true
        icon: si-qbittorrent
      - title: Radarr
        url: http://192.168.1.85:7878
        statusCheck: true
        icon: si-radarr
      - title: Sonarr
        url: http://192.168.1.85:8989
        statusCheck: true
        icon: si-radarr
      - title: Lidarr
        url: http://192.168.1.85:8686
        statusCheck: true
        icon: si-lidarr
  - name: Bookmarks
    icon: fas fa-bookmark
    items:
      - title: Arch Linux Launchpad
        url: http://192.168.1.227:9090
        icon: fas fa-rocket
      - title: Arch Desk Launchpad
        url: http://192.168.1.239:9090
        icon: fas fa-desktop
      - title: Raspberry4 Launchpad
        url: http://192.168.1.85:9090
        icon: fas fa-microchip
      - title: pyNance Dashroad
        url: http://192.168.1.239:3353
        icon: fas fa-chart-line
      - title: CapitalOne
        url: https://capitalone.com
        icon: fas fa-university
      - title: Fidelity
        url: https://fidelity.com/
        icon: fas fa-dollar-sign
      - title: OpenAI API Details
        url: https://platform.openai.com/usage
        icon: fas fa-brain
      - title: Github
        url: https://github.com/
        icon: fab fa-github
      - title: ChatGPT
        url: https://chatgpt.com/
        icon: fas fa-robot
      - title: Text Gen Webui
        url: http://192.168.1.239:7860
        icon: fas fa-terminal
pageInfo: {}
