appConfig:
  theme: colorful
  layout: auto
  iconSize: medium
  statusCheck: true
  showSplashScreen: false
  title: Dashy Dashroad
  header: Dashboard Landing
  footerText: goodDashroad

sections:
  - name: Weather
    icon: fas fa-cloud-sun
    widgets:
      - type: weather
        options:
          apiKey: ${WEATHER_API_KEY}
          city: Chapel Hill
          units: imperial
  - name: Service Status
    icon: fas fa-server
    items:
      - title: Jellyfin
        url: http://192.168.1.198:8097
        icon: si-jellyfin
      - title: Threadfin
        url: http://192.168.1.198:34400/web
        icon: fa-stream
      - title: JellyFindarr
        url: http://192.168.1.78:5505
        icon: mdi-antenna
      - title: qBittorrent
        url: http://192.168.1.198:8080
        icon: si-qbittorrent
      - title: Radarr
        url: http://192.168.1.198:7878
        icon: si-radarr
      - title: Sonarr
        url: http://192.168.1.198:8989
        icon: si-sonarr
      - title: Home Assistant
        url: http://192.168.1.198:8123
        icon: fas fa-home

  - name: Home Sensors
    icon: fas fa-bolt
    items:

  - name: Bookmarks
    icon: fas fa-bookmark
    items:
      - title: Arch Linux Launchpad
        url: http://192.168.1.228:9090
        icon: fas fa-rocket
      - title: Arch Desk Launchpad
        url: http://192.168.1.239:9090
        icon: fas fa-desktop
      - title: pyNance Dashroad
        url: http://192.168.1.239:3353
        icon: fas fa-chart-line
      - title: Text Gen WebUI
        url: http://192.168.1.68:7860
        icon: fas fa-terminal
      - title: CapitalOne
        url: https://capitalone.com
        icon: fas fa-university
      - title: Fidelity
        url: https://fidelity.com
        icon: fas fa-dollar-sign
      - title: OpenAI API Details
        url: https://platform.openai.com/usage
        icon: fas fa-brain
      - title: GitHub
        url: https://github.com
        icon: fab fa-github
      - title: ChatGPT
        url: https://chatgpt.com
        icon: fas fa-robot

  - name: System Tools
    icon: fas fa-cogs
    items:
      - title: DietPi Dashboard
        url: http://192.168.1.198:5252
        icon: fas fa-chart-pie
      - title: DietPi CloudShell
        url: http://192.168.1.198:5254
        icon: fas fa-terminal
      - title: Netdata
        url: http://192.168.1.198:19999
        icon: si-netdata
      - title: Gitea
        url: http://192.168.1.198:3000
        icon: si-gitea
      - title: Filebrowser
        url: http://192.168.1.198:8081
        icon: si-filebrowser
      - title: Portainer
        url: http://192.168.1.198:9000
        icon: si-portainer
      - title: Syncthing
        url: http://192.168.1.198:8384
        icon: si-syncthing
      - title: Demuxer
        url: http://192.168.1.198:9998
        icon: fas fa-film
      - title: Unmanic
        url: http://192.168.1.198:8888
        icon: si-unmanic

  - name: Email Monitor
    icon: fas fa-envelope-open-text
    widgets:
      - type: custom-list
        # Served by email_monitor/mbsync_status_server.py
        options:
          title: Mailboxes
          url: ${MAIL_STATUS_ENDPOINT}
          updateInterval: 180
          daysForNew: 2

